### ISSUE TITLE
Client::AUTH_HTTP_PASSWORD method

### ISSUE THREAD

**Issue by angmarian** [cdaguerre/php-trello-api#12]
I am trying to connect with Trello with AUTH_HTTP_PASSWORD method:

$this->client = new Client();
$this->client->authenticate($username, $password, Client::AUTH_HTTP_PASSWORD);

and get all user boards:

$boards = $this->client->api('member')->boards()->all('me');

But I get an error:
PHP Fatal error:  Uncaught exception 'Trello\Exception\RuntimeException' with message 'Invalid Authorization Header'

Is this a bug or Trello blocked this method?

**Comment by cdaguerre** [comment]
Hi @angmarian 
For now, only passing the token in the URL is implemented on Trello's side.
Please use :
```php
Client::AUTH_URL_CLIENT_ID
```

**Comment by hoangphuong** [comment]
Have you fixed?

**Comment by angmarian** [comment]
No, I use client id to connect, not username and password.
