### ISSUE TITLE
Error - New card

### ISSUE THREAD

**Issue by raalzate** [cdaguerre/php-trello-api#14]
Hello, I have trouble creating a new card, the error is: 

Fatal error: Uncaught exception 'Trello\Exception\RuntimeException' with message 'The requested resource was not found. ' in C:\xampp\htdocs\trello-api\vendor\cdaguerre\php-trello-api\lib\Trello\HttpClient\Listener\ErrorListener.php:62 Stack trace: #0 [internal function]: Trello\HttpClient\Listener\ErrorListener->onRequestError(Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 C:\xampp\htdocs\trello-api\vendor\symfony\event-dispatcher\EventDispatcher.php(164): call_user_func(Array, Object(Guzzle\Common\Event), 'request.error', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 C:\xampp\htdocs\trello-api\vendor\symfony\event-dispatcher\EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\Common\Event)) #3 C:\xampp\htdocs\trello-api\vendor\guzzle\guzzle\src\Guzzle\Http\Message\Request.php(589): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('request.error', Object(Guzzle\C in C:\xampp\htdocs\trello-api\vendor\cdaguerre\php-trello-api\lib\Trello\HttpClient\HttpClient.php on line 152

**Comment by cdaguerre** [comment]
Hi @raalzate 
Could you post the piece of code causing this issue?

**Comment by raalzate** [comment]
Yes, the full syntax is:

require "vendor/autoload.php";

use Trello\Client;
use Trello\Manager;

$client = new Client();
$client->authenticate('dbf215f2aaa98d36802bc43805082964', 'a666d59137099f083e1b4a1f6671cc031d25e743cd78c95250563f1fe27d1005', Client::AUTH_URL_CLIENT_ID);

$boards = $client->api('member')->boards()->all("raulaalzate");

$manager = new Manager($client);
echo $boards[8]['id'];

$card = $client->api('card')->show($boards[8]['id'], array('fields' => 'all'));
print_r($card );

--
 thank you.

**Comment by cdaguerre** [comment]
Not sure what you are trying to do.
If you are trying to get all cards associated to a board, you should call:
```php
$cards = $client->api('board')->cards()->all($boards[8]['id']);
```

**Comment by cdaguerre** [comment]
By calling 
```php
$card = $client->api('card')->show($boards[8]['id']);
```
you are trying to retrieve a card by giving the id of a board, that's why it's not found.

**Comment by raalzate** [comment]
thank you, works perfect.

**Comment by cdaguerre** [comment]
:+1:
