### ISSUE TITLE
Webhook JSON body not being parsed?

### ISSUE THREAD

**Issue by robolmos** [cdaguerre/php-trello-api#50]
I'm not sure if the Trello API was updated recently but the webhooks were not working out of the box. I needed to modify the Service::handleWebhook method to be like this:

```php
if (!$request) {
    $request = Request::createFromGlobals();
    $data = json_decode($request->getContent(), true);
    $request->request->replace($data);
}
```

**Comment by mikzero** [comment]
Good job.
Now it works again.
