### ISSUE TITLE
Trello/Api/Card will throw an exception when due date is not null

### ISSUE THREAD

**Issue by ogabrielsantos** [cdaguerre/php-trello-api#7]
`Trello/Model/Card.php` expects a due date as `DateTime` but `Trello/Api/Card` does not convert the object to a valid string. When `create` or `update` is called, Guzzle throws an exception because can't handle the `DateTime` object.

     [Symfony\Component\Debug\Exception\FatalErrorException]                          
     Error: Method Guzzle\Http\QueryString::__toString() must not throw an exception

Can I send a PR?

**Comment by cdaguerre** [comment]
@ogabrielsantos Sure, be my guest! Thanks

**Comment by ogabrielsantos** [comment]
Maybe you can review and merge the pull request.

**Comment by ogabrielsantos** [comment]
PR Merged. Issue closed.

**Comment by ogabrielsantos** [comment]
I've reopened this issue in order to warn about wrong DateTime's timezone. I've already sent a PR (#10)

**Comment by cdaguerre** [comment]
Closed by #10
