### ISSUE TITLE
Package abandoned?

### ISSUE THREAD

**Issue by LightAir** [cdaguerre/php-trello-api#77]
if this project do not maintained, please set as abandoned in the packagist.org
thx

**Comment by matteocacciola** [comment]
@benrowe If you want, I forked this repo in order to make it working with Symfony 5 and PHP 7. I can give it a go to maintain it: https://github.com/matteocacciola/php-trello-api

**Comment by cdaguerre** [comment]
@matteocacciola just gave you maintainer access to this repository!
