### ISSUE TITLE
Error when using API key and Token

### ISSUE THREAD

**Issue by matteocacciola** [cdaguerre/php-trello-api#83]
Hello, I am trying to use the package by key and token.
I have taken the API key from https://trello.com/app-key. I have taken the token by https://trello.com/1/authorize?expiration=never&scope=read,write,account&response_type=token&name=Server%20Token&key=<api_key>

Now, I use the following way for interfacing with Trello API:
`$client->authenticate('apiKey', 'token', Client::AUTH_URL_CLIENT_ID);`

I have an unauthenticated error. What am I missing, please?

**Comment by LuongTranNguyen** [comment]
Can you share detail of this unauthenticated error.

You can check you token and api_key by this curl : curl 'https://api.trello.com/1/members/me/boards?fields=name,url&key=YOUR_API_KEY&token=YOUR_TOKEN'

**Comment by matteocacciola** [comment]
There was a problem with the GuzzleHttp library. They switched to use
subscribers for HTTP requests, and no more listeners.

I have updated my fork and now everything works as expected.
